# Private service connection for Memorystore
resource "google_compute_global_address" "redis_private_ip" {
  name          = "${var.environment}-redis-private-ip"
  project       = var.project_id
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 16
  network       = "projects/${var.project_id}/global/networks/default"
  depends_on    = [google_project_service.compute]
}

resource "google_service_networking_connection" "redis_private_vpc" {
  network                 = "projects/${var.project_id}/global/networks/default"
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.redis_private_ip.name]
  depends_on              = [google_project_service.servicenetworking]
}

# Store Redis auth string in Secret Manager  
# The auth string will be auto-generated by the Redis instance
resource "google_secret_manager_secret" "redis_auth_secret" {
  secret_id = "${var.environment}-redis-auth"
  project   = var.project_id
  replication {
    auto {}
  }
  depends_on = [google_project_service.secretmanager]
}

resource "google_secret_manager_secret_version" "redis_auth_secret_version" {
  secret      = google_secret_manager_secret.redis_auth_secret.id
  secret_data = google_redis_instance.default.auth_string
}

# Memorystore for Redis instance
resource "google_redis_instance" "default" {
  name               = "${var.environment}-redis-instance"
  project            = var.project_id
  tier               = var.redis_tier
  memory_size_gb     = var.redis_memory_size_gb
  region             = var.region
  location_id        = "${var.region}-a"
  redis_version      = "REDIS_7_0"
  display_name       = "${var.environment} Redis Instance"
  auth_enabled       = true
  transit_encryption_mode = "SERVER_AUTHENTICATION"
  
  # Connect to the private VPC
  authorized_network = "projects/${var.project_id}/global/networks/default"
  connect_mode       = "PRIVATE_SERVICE_ACCESS"
  
  depends_on = [
    google_project_service.redis,
    google_service_networking_connection.redis_private_vpc
  ]
}

# Outputs
output "redis_host" {
  description = "The IP address of the Redis instance"
  value       = google_redis_instance.default.host
  sensitive   = true
}

output "redis_port" {
  description = "The port of the Redis instance"
  value       = google_redis_instance.default.port
}

output "redis_auth_secret_name" {
  description = "The name of the secret containing the Redis auth string"
  value       = google_secret_manager_secret.redis_auth_secret.secret_id
}

output "redis_instance_name" {
  description = "The name of the Redis instance"
  value       = google_redis_instance.default.name
}